### ISSUE TITLE
Cannot read properties of undefined (reading 'B') after update library to 1.0.30001655 version

### ISSUE THREAD

**Issue by andrewst** [browserslist/caniuse-lite#129]
We started getting errors after updating the library from 1.0.30001653 to 1.0.30001655.

`TypeError: Cannot read properties of undefined (reading 'B')
    at Module.unpackFeature (my-project/node_modules/.pnpm/caniuse-lite@1.0.30001655/node_modules/caniuse-lite/dist/unpacker/feature.js:31:29)
    at BrowserSelection.compileBrowserSupport (file://my-project/node_modules/.pnpm/doiuse@6.0.2/node_modules/doiuse/lib/BrowserSelection.js:148:35)
    at BrowserSelection.missingSupport (file://my-project/node_modules/.pnpm/doiuse@6.0.2/node_modules/doiuse/lib/BrowserSelection.js:178:27)
    at DoIUse.postcss (file://my-project/node_modules/.pnpm/doiuse@6.0.2/node_modules/doiuse/lib/DoIUse.js:67:43)
    at file://my-project/node_modules/.pnpm/stylelint-no-unsupported-browser-features@8.0.1_stylelint@16.8.1/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:99:27
    at file://my-project/node_modules/.pnpm/stylelint@16.8.1_typescript@5.5.4/node_modules/stylelint/lib/lintPostcssResult.mjs:112:8
    at Array.map (<anonymous>)
    at lintPostcssResult (file://my-project/node_modules/.pnpm/stylelint@16.8.1_typescript@5.5.4/node_modules/stylelint/lib/lintPostcssResult.mjs:102:18)
    at async lintSource (file://my-project/node_modules/.pnpm/stylelint@16.8.1_typescript@5.5.4/node_modules/stylelint/lib/lintSource.mjs:108:2)
    at async file://my-project/node_modules/.pnpm/stylelint@16.8.1_typescript@5.5.4/node_modules/stylelint/lib/standalone.mjs:236:27`

**Comment by ai** [comment]
It happened because `caniuse-db` deleted some information, which was used by `stylelint-no-unsupported-browser-features`

https://github.com/Fyrd/caniuse/commit/0a84cfd3b2b3abb650787abdc39faf382800e8cd

You need to open an issue in `stylelint-no-unsupported-browser-features`

**Comment by andrewst** [comment]
https://github.com/RJWadley/stylelint-no-unsupported-browser-features/issues/299

**Comment by Jameskmonger** [comment]
My recommendation to users of `caniuse-lite` would be to **always** rely on a specific version rather than accepting a version range (e.g. `~` or `^`).

This was a breaking change published under a patch update (`1.0.30001654` -> `1.0.30001655`)

**Comment by dkrnl** [comment]
temporal fix: `npm i caniuse-lite@1.0.30001653 --save-exact`
