### ISSUE TITLE
Return css-scroll-timeline

### ISSUE THREAD

**Issue by Opty1712** [browserslist/caniuse-lite#133]
Hello I have an error while linting code:

```
$ stylelint "**/*.{css,scss}"
TypeError: Cannot read properties of undefined (reading 'B')
    at Object.unpackFeature (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/caniuse-lite/dist/unpacker/feature.js:31:29)
    at BrowserSelection.compileBrowserSupport (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/doiuse/exports/index.cjs:2578:46)
    at BrowserSelection.missingSupport (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/doiuse/exports/index.cjs:2608:27)
    at DoIUse.postcss (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/doiuse/exports/index.cjs:2828:43)
    at /Users/a.edunov/work/RUSTORE/monorepo/node_modules/stylelint-no-unsupported-browser-features/lib/index.js:86:27
    at /Users/a.edunov/work/RUSTORE/monorepo/node_modules/stylelint/lib/lintPostcssResult.js:121:8
    at Array.map (<anonymous>)
    at lintPostcssResult (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/stylelint/lib/lintPostcssResult.js:111:18)
    at lintSource (/Users/a.edunov/work/RUSTORE/monorepo/node_modules/stylelint/lib/lintSource.js:110:8)
    at async /Users/a.edunov/work/RUSTORE/monorepo/node_modules/stylelint/lib/standalone.js:211:27
```
After investigating of what happens I found out that it works this way:
`stylelint` → `doiuse` → `caniuse-lite`. 

 `doiuse` has this feature [css-scroll-timeline](https://github.com/anandthakker/doiuse/blob/master/data/features/css-scroll-timeline.js), but `caniuse-lite` has not since version 1.0.30001655.

Can you please roll it back?

https://github.com/browserslist/caniuse-lite/compare/1.0.30001654...1.0.30001655

**Comment by ai** [comment]
I can't. We are just re-pack of `caniuse-db`. You need to ask them.

**Comment by Opty1712** [comment]
Thank you, sure. According to PRs there 

https://github.com/Fyrd/caniuse/pull/6956
https://github.com/Fyrd/caniuse/commit/0a84cfd3b2b3abb650787abdc39faf382800e8cd

it seems that I have to ask [doiuse](https://github.com/anandthakker/doiuse/) to make a release
