### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by abhi9bakshi** [browserslist/caniuse-lite#25]
I am using the package with node 10.16.0, npm 6.9.0 in Windows on https://github.com/maximegris/angular-electron.

If I run `npm run start` i gert the following error

```
missing ) after argument list
C:\Users\Admin\Downloads\angular-electron\node_modules\caniuse-lite\data\features\srcset.js:4
        /* [retval, out] */__RPC__deref_out_opt __x_ABI_CWindows_CFoundation_CIUriRuntimeClass * * value
                           ^^^^^^^^^^^^^^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Admin\Downloads\angular-electron\node_modules\caniuse-lite\data\features.js:1:23438)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Admin\Downloads\angular-electron\node_modules\caniuse-lite\dist\unpacker\features.js:11:35)
```

**Comment by ai** [comment]
Is it still actual?
