### ISSUE TITLE
TypeError: region is not a function (from browserslist)

### ISSUE THREAD

**Issue by romainmenke** [browserslist/caniuse-lite#73]
I think this is related or the same issue as #70 

versions :
- `caniuse-lite@1.0.30001226`
- `browserslist@4.16.6`

`TypeError: region is not a function`

Trace :

```
TypeError: region is not a function
    at Object.loadCountry (/node_modules/browserslist/node.js:234:23)
    at Function.select (/node_modules/browserslist/index.js:898:11)
    at /node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/node_modules/browserslist/index.js:318:18)
    at browserslist (/node_modules/browserslist/index.js:444:21)
    at /node_modules/postcss-preset-env/index.js:434:29
    at creator (/node_modules/postcss/lib/postcss.js:133:35)
```

Code from browserslist :

https://github.com/browserslist/browserslist/blob/main/node.js#L234

```js
var feature = require('caniuse-lite/dist/unpacker/feature').default
var region = require('caniuse-lite/dist/unpacker/region').default

var compressed = require('caniuse-lite/data/regions/' + code + '.js')
var usageData = region(compressed)
```

**Comment by ai** [comment]
Fixed  1114c93ed
